name: On Code Change

on:
  pull_request:
    type: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: CICD
      - name: Navigate to src folder
        shell: bash
        run: |
          cd src
      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.4.0
        with:
          style: file
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: CICD
      - name: Build
        shell: bash
        run: |
          ls -al
          cd src
          make